// GENERATED by tool/export_lore_menu.py -- 원작 LOREMENU.PAS 문구
// 표시/선택창 문구를 원문 그대로 쓰기 위한 상수 모음.

/// 원작 `LOREMENU.PAS` 의 화면 문구(원문).
class LoreMenuText {
  const LoreMenuText._();

  static const String selectModePrompt = '당신의 명령을 고르시오 ===>';
  static const String selectModeParty = '일행의 상황을 본다';
  static const String selectModeCharacter = '개인의 상황을 본다';
  static const String selectModeQuick = '일행의 건강 상태를 본다';
  static const String selectModeCast = '마법을 사용한다';
  static const String selectModeEsp = '초능력을 사용한다';
  static const String selectModeRest = '여기서 쉰다';
  static const String selectModeOption = '게임 선택 상황';
  static const String viewPartyXAxis = 'X 축 = ';
  static const String viewPartyYAxis = 'Y 축 = ';
  static const String viewPartyFood = '남은 식량 = ';
  static const String viewPartyGold = '남은 황금 = ';
  static const String viewPartyTorch = '마법의 횃불 :';
  static const String viewPartyLevitate = '공중 부상   :';
  static const String viewPartyWater = '물위를 걸음 :';
  static const String viewPartySwamp = '늪위를 걸음 :';
  static const String viewPartyAvailable = ' 가능';
  static const String viewPartyUnavailable = ' 불가';
  static const String viewCharWho = '능력을 보고싶은 인물을 선택하시오';
  static const String viewCharName = '# 이름 : ';
  static const String viewCharSex = '# 성별 : ';
  static const String viewCharClass = '# 계급 : ';
  static const String viewCharStrength = '체력   : ';
  static const String viewCharMentality = '정신력 : ';
  static const String viewCharConcentration = '집중력 : ';
  static const String viewCharEndurance = '인내력 : ';
  static const String viewCharResistance = '저항력 : ';
  static const String viewCharAgility = '민첩성 : ';
  static const String viewCharLuck = '행운   : ';
  static const String viewCharPressKey = '아무키나 누르십시오 ...';
  static const String viewCharAccArms = '무기의 정확성   : ';
  static const String viewCharAccMagic = '정신력의 정확성 : ';
  static const String viewCharAccEsp = '초감각의 정확성 : ';
  static const String viewCharBattleLevel = '전투 레벨   : ';
  static const String viewCharMagicLevel = '마법 레벨   : ';
  static const String viewCharEspLevel = '초감각 레벨 : ';
  static const String viewCharExp = '## 경험치   : ';
  static const String viewCharWeapon = '사용 무기 - ';
  static const String viewCharShield = '방패 - ';
  static const String viewCharArmor = '갑옷 - ';
  static const String viewCharShieldSuffix = ' 방패';
  static const String viewCharArmorSuffix = ' 갑옷';
  static const String quickViewName = '이름';
  static const String quickViewHeader = ' 중독 의식불명 죽음';
  static const String castSpellKind = '사용할 마법의 종류 ===>';
  static const String castSpellAttack = '공격 마법';
  static const String castSpellCure = '치료 마법';
  static const String castSpellPhenomina = '변화 마법';
  static const String castSpellNotReady = '는 마법을 사용할수있는 상태가 아닙니다';
  static const String espNotEnough = 'ESP 지수가 충분하지 않습니다.';
  static const String espNotReady = '는 초감각을 사용할수있는 상태가 아닙니다';
  static const String espNoAbility = '당신에게는 아직 능력이 없습니다.';
  static const String espBattleOnly = '은 전투 모드에서만 사용됩니다.';
  static const String espSeeThrough = '일행은 주위를 투시하고 있다.';
  static const String espMindRead = '당신은 잠시동안 다른 사람의 마음을 읽을수 있다.';
  static const String espDirection = '<<<  방향을 선택하시오  >>>';
  static const String espClairvoyanceUse = '으로 천리안을 사용';
  static const String espClairvoyanceBusy = '천리안의 사용중 ...';
  static const String espPressKey = '아무키나 누르시오 ...';
  static const String espKind = '사용할 초감각의 종류 ===>';
  static const String espEvilPower = ' 이 동굴의 악의 힘이 이 마법을 방해합니다.';
  static const String phenominaSelect = '선택';
  static const String phenominaVaporize = '으로 기화 이동';
  static const String phenominaTerrain = '에 지형 변화';
  static const String phenominaSpaceMove = '으로 공간이동';
  static const String phenominaRejected = '알수없는 힘이 당신의 마법을 배척합니다.';
  static const String phenominaTorch = '일행은 마법의 횃불을 밝혔습니다.';
  static const String phenominaLevitate = '일행은 공중부상중 입니다.';
  static const String phenominaWater = '일행은 물위를 걸을수 있습니다.';
  static const String phenominaSwamp = '일행은 늪위를 걸을수 있습니다.';
  static const String phenominaVaporizeFail = '기화 이동이 통하지 않습니다.';
  static const String phenominaVaporizeDone = '기화 이동을 마쳤습니다.';
  static const String phenominaTerrainDone = '지형 변화에 성공했습니다.';
  static const String phenominaPowerPrompt = '당신의 공간 이동력을 지정';
  static const String phenominaXAxis = 'X 축 = ';
  static const String phenominaYAxis = 'Y 축 = ';
  static const String optionTitle = '게임 선택 상황';
  static const String optionDifficulty = '난이도 조절';
  static const String optionOrder = '정식 일행의 순서 정렬';
  static const String optionRemove = '일행에서 제외 시킴';
  static const String optionResume = '이전의 게임을 재개';
  static const String optionSave = '현재의 게임을 저장';
  static const String optionQuit = '게임을 마침';
  static const String optionMaxEnemy1 = '한번에 출현하는 적들의';
  static const String optionMaxEnemy2 = '최대치를 기입하십시오';
  static const String optionEnemySuffix = ' 명의 적들';
  static const String optionEncounterPrompt = '일행들의 지금 성격은 어떻습니까 ?';
  static const String optionEncounter1 = '일부러 전투를 피하고 싶다';
  static const String optionEncounter2 = '너무 잦은 전투는 원하지 않는다';
  static const String optionEncounter3 = '마주친 적과는 전투를 하겠다';
  static const String optionEncounter4 = '보이는 적들과는 모두 전투하겠다';
  static const String optionEncounter5 = '그들은 피에 굶주려 있다';
  static const String optionOrderPrompt = '현재의 일원의 전투 순서를 정렬 하십시오.';
  static const String optionOrderWho = '순서를 바꿀 일원';
  static const String optionRemovePrompt = '일행에서 제외 시키고 싶은 사람을 고르십시오.';
  static const String optionLoadPrompt = '게임의 저장 장소를 선택하십시오.';
  static const String optionSaving = '현재의 게임을 저장합니다';
  static const String optionSaveDone = '성공했습니다';
  static const String optionReserved = 'Reserved';
  static const String restNoFood = '일행은 식량이 바닥났다';
  static const String restPressKey = '아무키나 누르시오 ...';

  /// 원작 `ReturnMagic`(LORESUB.PAS) 이름(41..45 = 초감각 5종).
  static const List<String> espNames = [
    '투시',
    '예언',
    '독심',
    '천리안',
    '염력',
  ];

  /// 원작 `ReturnMagic` 이름(33..40 = 변화 마법 8종).
  static const List<String> phenominaNames = [
    '마법의 햇불',
    '공중 부상',
    '물위를 걸음',
    '늪위를 걸음',
    '기화 이동',
    '지형 변화',
    '공간 이동',
    '식량 제조',
  ];
}
