// GENERATED by tool/export_lore_batt.py -- 원작 LOREBATT.PAS 전투 문구

/// 원작 `LOREBATT.PAS` 의 전투 로그 조각(원문).
///
/// 원작은 조각을 이어붙여 문장을 만든다. 포트도 같은 문장이 나오도록
/// 아래 헬퍼를 통해 조합한다.
class LoreBattText {
  const LoreBattText._();

  static const String expGainedMsg = '만큼 경험치를 얻었다 !';
  static const String goldGained = '개의 금을 얻었다.';
  static const String killWeapon = '의 무기가 ';
  static const String killHeart = '의 심장을 꿰뚫었다';
  static const String killHead = '의 머리는 ';
  static const String killHeadRest = '의 공격으로 산산 조각이 났다';
  static const String killBlood = '적의 피가 사방에 뿌려졌다';
  static const String killTorn = '적은 비명과 함께 찢겨 나갔다';
  static const String attackMissed = '의 공격은 빗나갔다 ....';
  static const String enemyResisted = '적은 ';
  static const String enemyResistedRest = '의 공격을 저지했다';
  static const String enemyBlocked = '그러나, 적은 ';
  static const String enemyBlockedRest = '의 공격을 막았다';
  static const String enemyKnockedOut = '적은 ';
  static const String enemyKnockedOutRest = '의 공격으로 의식불명이 되었다';
  static const String enemyDamaged = '적은 ';
  static const String enemyDamagedRest = '만큼의 피해를 입었다';
  static const String magicOnCorpse = '의 마법은 적의 시체 위에서 작열했다';
  static const String spNotEnough = '마법 지수가 부족했다';
  static const String magicMissed = '그러나, ';
  static const String magicMissedRest = '를 빗나갔다';
  static const String enemyResistedMagic = '는 ';
  static const String enemyResistedMagicRest = '의 마법을 저지했다';
  static const String enemyBlockedMagic = '그러나, ';
  static const String enemyBlockedMagicRest = '는 ';
  static const String enemyBlockedMagicTail = '의 마법 공격을 막았다';
  static const String magicKnockedOut = '는 ';
  static const String magicKnockedOutRest = '의 마법에 의해 의식불능이 되었다';
  static const String magicDamaged = '는 ';
  static const String magicDamagedRest = '만큼의 피해를 입었다';
  static const String noAbility = '당신에게는 아직 능력이 없다.';
  static const String poisonResisted = '적은 독 공격을 저지 했다';
  static const String poisonMissed = '독 공격은 빗나갔다';
  static const String poisoned = '는 중독 되었다';
  static const String techResisted = '기술 무력화 공격은 저지 당했다';
  static const String techMissed = '기술 무력화 공격은 빗나갔다';
  static const String techRemoved = '의 특수 공격 능력이 제거되었다';
  static const String defenseResisted = '방어 무력화 공격은 저지 당했다';
  static const String defenseMissed = '방어 무력화 공격은 빗나갔다';
  static const String defenseLowered = '의 방어 능력이 저하되었다';
  static const String powerResisted = '능력 저하 공격은 저지 당했다';
  static const String powerMissed = '능력 저하 공격은 빗나갔다';
  static const String powerLowered = '의 전체적인 능력이 저하되었다';
  static const String magicBanResisted = '마법 불능 공격은 저지 당했다';
  static const String magicBanMissed = '마법 불능 공격은 빗나갔다';
  static const String magicLowered = '의 마법 능력이 저하되었다';
  static const String magicRemoved = '의 마법 능력은 사라졌다';
  static const String espBanResisted = '탈 초인화 공격은 저지 당했다';
  static const String espBanMissed = '탈 초인화 공격은 빗나갔다';
  static const String espLowered = '의 초자연적 능력이 저하되었다';
  static const String espRemoved = '의 초자연적 능력은 사라졌다';
  static const String espBattleOnly = '는 전투모드에서는 사용할 수가 없습니다.';
  static const String espNotEnough = '초감각 지수가 부족했다';
  static const String mindReadFailed = '독심술은 전혀 통하지 않았다';
  static const String mindReadWeak = '적의 마음을 끌어들이기에는 아직 능력이 부족했다';
  static const String mindReadResisted = '적의 마음은 흔들리지 않았다';
  static const String mindReadJoined = '적은 우리의 편이 되었다';
  static const String espRocks = '주위의 돌들이 떠올라 ';
  static const String espRocksRest = '를 공격하기 시작한다';
  static const String espGerms = ' 주위의 세균이 그에게 침투하여 해를 입히기 시작한다';
  static const String espWeapon = '의 무기가 갑자기 ';
  static const String espWeaponRest = '에게 달려들기 시작한다';
  static const String espFission = '갑자기 땅속의 우라늄이 핵분열을 일으켜 고온';
  static const String espFissionRest = '의 열기가 적의 주위를 감싸기 시작한다';
  static const String espFusion = '공기중의 수소가 돌연히 핵융합을 일으켜 질량';
  static const String espFusionRest = '결손의 에너지를 적들에게 방출하기 시작한다';
  static const String espFear = '는 적에게 공포심을 불어 넣었다';
  static const String espFled = '는 겁을 먹고는 도망 가버렸다';
  static const String espMetabolism = '는 적의 신진 대사를 조절하여 적의 ';
  static const String espMetabolismRest = '체력을 점차 약화 시키려 한다';
  static const String espHeart = '는 염력으로 적의 심장을 멈추려 한다';
  static const String espIllusion = '는 적을 환상속에 빠지게 하려한다';
  static const String runFailed = '그러나, 일행은 성공하지 못했다';
  static const String runSuccess = '성공적으로 도망을 갔다';
  static const String partyMissed = '는 빗맞추었다';
  static const String enemyAttacked = '는 ';
  static const String enemyAttackedRest = '를 공격했다';
  static const String partyResisted = '그러나, ';
  static const String partyResistedRest = '는 적의 공격을 저지했다';
  static const String partyBlockedRest = '는 적의 공격을 방어했다';
  static const String partyWasAttacked = '는 ';
  static const String partyWasAttackedRest = '에게 공격 받았다';
  static const String partyDamaged = '는 ';
  static const String partyDamagedRest = '만큼의 피해를 입었다';
  static const String enemyMagicMissed = '의 마법공격은 빗나갔다';
  static const String partyResistedEnemyMagic = '그러나, ';
  static const String partyResistedEnemyMagicRest = '는 적의 마법을 저지했다';
  static const String partyBlockedEnemyMagicRest = '는 적의 마법을 막아냈다';
  static const String enemyMagicUsed = '는 ';
  static const String enemyMagicUsedRest = "에게 '";
  static const String enemyMagicUsedTail = "'마법을 사용했다";
  static const String enemyMagicAll = "는 일행 모두에게 '";
  static const String enemyMagicAllTail = "'마법을 사용했다";
  static const String enemyHealSelf = '는 자신을 치료했다';
  static const String enemyHealOther = '는 ';
  static const String enemyHealOtherRest = '를 치료했다';
  static const String armorBreakTry = '는 ';
  static const String armorBreakTryRest = '의 갑옷파괴를 시도했다';
  static const String armorBreakFail = '그러나, ';
  static const String armorBreakFailRest = '는 성공하지 못했다';
  static const String armorBroken = '의 갑옷은 파괴되었다';
  static const String poisonTry = '는 ';
  static const String poisonTryRest = '에게 독 공격을 시도했다';
  static const String poisonFail = '독 공격은 실패했다';
  static const String poisonAvoid = '그러나, ';
  static const String poisonAvoidRest = '는 독 공격을 피했다';
  static const String poisonedBang = '는 중독 되었다 !!';
  static const String fatalTry = '는 ';
  static const String fatalTryRest = '에게 치명적 공격을 시도했다';
  static const String fatalFail = '치명적 공격은 실패했다';
  static const String fatalAvoid = '그러나, ';
  static const String fatalAvoidRest = '는 치명적 공격을 피했다';
  static const String fatalDone = '는 의식불명이 되었다 !!';
  static const String deathTry = '는 ';
  static const String deathTryRest = '에게 죽음의 공격을 시도했다';
  static const String deathFail = '죽음의 공격은 실패했다';
  static const String deathAvoid = '그러나, ';
  static const String deathAvoidRest = '는 죽음의 공격을 피했다';
  static const String deathDone = '는 죽었다 !!';
  static const String summonTry = '는 ';
  static const String summonTryRest = '를 생성시켰다';
  static const String mindReadEnemy = '가 독심술을 사용하여 ';
  static const String mindReadEnemyRest = '을 자기편으로 끌어들였다';
  static const String battleMode = '의 전투 모드 ===>';
  static const String menuAttackOne = '한 명의 적을 ';
  static const String menuAttackOneRest = '로 공격';
  static const String menuMagicOne = '한 명의 적에게 마법 공격';
  static const String menuMagicAll = '모든 적에게 마법 공격';
  static const String menuSpecial = '적에게 특수 마법 공격';
  static const String menuHealParty = '일행을 치료';
  static const String menuEsp = '적에게 초능력 사용';
  static const String menuRun = '도망을 시도함';
  static const String menuCommandAll = '일행에게 무조건 공격 할 것을 지시';
  static const String menuNone = '없음';
  static const String encounter = '적이 출현했다 !!!';
  static const String enemyAgility = '적의 평균 민첩성';
  static const String engage = '적과 교전한다';
  static const String flee = '도망간다';

  /// 원작 `ReturnSexData` - 성별에 따른 호칭.
  static String sexData(bool female) => female ? '그녀' : '그';

  /// 원작 `AttackOne` 1) 무기로 적 처치(4종 연출 중 1종).
  static String weaponKill(String sex, String target, int roll) {
    switch (roll % 4) {
      case 0:
        return '$sex$killWeapon$target$killHeart';
      case 1:
        return '$target$killHead$sex$killHeadRest';
      case 2:
        return killBlood;
      default:
        return killTorn;
    }
  }

  /// 원작 `{actor}는 {amount}만큼 경험치를 얻었다 !`.
  static String expGained(String actor, String amount) =>
      '$actor는 $amount$expGainedMsg';

  /// 원작 `일행은 {n}개의 금을 얻었다.`
  static String goldFound(String amount) => '일행은 $amount$goldGained';
}
