#!/usr/bin/env python3
"""Execute the unmodified integer Random routine from LORE.EXE in x86-16.
Generation requires `pip install unicorn`; --check needs only the standard library.
No game saves, original EXE bytes or clock are modified.
"""
import argparse
import hashlib
import json
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'test/fixtures/dos_random_stream.json'
VERIFY = ROOT / 'tool/verify_source_random.dart'

def build():
    from unicorn import Uc, UC_ARCH_X86, UC_MODE_16, UC_HOOK_CODE
    from unicorn.x86_const import (
        UC_X86_REG_AX, UC_X86_REG_CS, UC_X86_REG_DS, UC_X86_REG_IP,
        UC_X86_REG_SP, UC_X86_REG_SS,
    )

    executable = (ROOT / 'repo_source/LORE_1993_runtime/LORE.EXE').read_bytes()
    # File offsets located by disassembling the shipped 16-bit executable.
    image_offset = 221248
    entry_offset = 225719 - image_offset
    return_offset = 225738 - image_offset
    assert executable[225852:225854] == bytes.fromhex('0584')
    cases = []
    for seed in [0, 1, 65535, 65536, 0x7fffffff, 0x80000000, 0xffffffff, 0xdeadbeef]:
        vm = Uc(UC_ARCH_X86, UC_MODE_16)
        vm.mem_map(0, 0x50000)
        vm.mem_write(0x10000, executable[image_offset:image_offset + 0x2000])
        vm.reg_write(UC_X86_REG_CS, 0x1000)
        vm.reg_write(UC_X86_REG_DS, 0x2000)
        vm.reg_write(UC_X86_REG_SS, 0x3000)
        vm.reg_write(UC_X86_REG_SP, 0xff00)
        vm.mem_write(0x20000 + 0x364c, struct.pack('<I', seed))

        def stop_at_far_return(machine, address, size, data):
            if address == 0x10000 + return_offset:
                machine.emu_stop()

        vm.hook_add(UC_HOOK_CODE, stop_at_far_return)
        values = []
        for bound in [0, 1, 20, 40, 65535, 2, 3, 9, 100, 1000, 256, 0]:
            # The Word argument is four bytes above SP (past the far return).
            vm.mem_write(0x30000 + 0xff04, struct.pack('<H', bound))
            vm.emu_start(0x10000 + entry_offset, 0x10000 + return_offset + 3, count=200)
            if vm.reg_read(UC_X86_REG_IP) != return_offset:
                raise RuntimeError('Original Random did not reach its far return')
            values.append({
                'bound': bound,
                'value': vm.reg_read(UC_X86_REG_AX),
                'seed': struct.unpack('<I', vm.mem_read(0x20000 + 0x364c, 4))[0],
            })
        cases.append({'initialSeed': seed, 'calls': values})
    return {
        'source': 'Unmodified LORE.EXE integer Random routine executed by Unicorn x86-16',
        'executableSha256': hashlib.sha256(executable).hexdigest(),
        'routine': {
            'csImageFileOffset': image_offset,
            'randomFileOffset': 225719,
            'advanceFileOffset': 225798,
            'multiplierFileOffset': 225852,
            'randSeedDataOffset': 0x364c,
            'codeHex': executable[225719:225852].hex(),
        },
        'cases': cases,
    }


def verifier(fixture):
    encoded = json.dumps(fixture['cases'], separators=(',', ':'))
    return """// GENERATED by tool/export_dos_random_stream.py from original EXE execution.
import 'dart:convert';
import 'package:lore/logic/lore_random.dart';

void main() {
  final cases = jsonDecode(r'''""" + encoded + """''') as List;
  var count = 0;
  for (final scenario in cases) {
    final random = LoreRandom(scenario['initialSeed'] as int);
    for (final call in scenario['calls'] as List) {
      final actual = random.nextInt(call['bound'] as int);
      if (actual != call['value'] || random.seed != call['seed']) {
        throw StateError('Original EXE random stream mismatch at call $count');
      }
      count++;
    }
  }
  // ignore: avoid_print
  print('Original EXE random stream: $count calls match');
}
"""

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if args.check:
        fixture = json.loads(OUTPUT.read_text())
        executable = (ROOT / 'repo_source/LORE_1993_runtime/LORE.EXE').read_bytes()
        assert hashlib.sha256(executable).hexdigest() == fixture['executableSha256']
        routine = fixture['routine']
        assert executable[routine['randomFileOffset']:routine['multiplierFileOffset']].hex() == routine['codeHex']
        assert executable[routine['multiplierFileOffset']:routine['multiplierFileOffset']+2] == bytes.fromhex('0584')
        assert VERIFY.read_text() == verifier(fixture)
        print('Original EXE random fixture and verifier are current')
    else:
        fixture = build()
        OUTPUT.write_text(json.dumps(fixture, indent=2) + '\n')
        VERIFY.write_text(verifier(fixture))

if __name__ == '__main__':
    main()
