/// 1993년 원작의 enemydata1(도감 템플릿) 및 enemydata2(전투 인스턴스)에 대응하는 Monster 모델
class Monster {
  final int eNumber;
  final String name;
  final int strength;
  final int mentality;
  final int endurance;
  int resistance;
  int agility;
  int accArms;
  int accMagic;
  int ac;
  int special;
  int castLevel;
  int specialCastLevel;
  int level;

  int hp;
  final int maxHp;
  bool isPoisoned;
  bool isUnconscious;
  bool isDead;

  Monster({
    required this.eNumber,
    required this.name,
    required this.strength,
    required this.mentality,
    required this.endurance,
    required this.resistance,
    required this.agility,
    required this.accArms,
    required this.accMagic,
    required this.ac,
    required this.special,
    required this.castLevel,
    required this.specialCastLevel,
    required this.level,
    int? hp,
    this.isPoisoned = false,
    this.isUnconscious = false,
    this.isDead = false,
  }) : maxHp = endurance * (level > 0 ? level : 1),
       hp = hp ?? (endurance * (level > 0 ? level : 1));

  Monster copyWith({
    int? hp,
    bool? isPoisoned,
    bool? isUnconscious,
    bool? isDead,
  }) {
    return Monster(
      eNumber: eNumber,
      name: name,
      strength: strength,
      mentality: mentality,
      endurance: endurance,
      resistance: resistance,
      agility: agility,
      accArms: accArms,
      accMagic: accMagic,
      ac: ac,
      special: special,
      castLevel: castLevel,
      specialCastLevel: specialCastLevel,
      level: level,
      hp: hp ?? this.hp,
      isPoisoned: isPoisoned ?? this.isPoisoned,
      isUnconscious: isUnconscious ?? this.isUnconscious,
      isDead: isDead ?? this.isDead,
    );
  }

  /// 원작 `with enemy[i] do begin name := 'Sphinx'; level := 4; ac := 8; end`
  /// 같은 **적별 덮어쓰기**를 적용한 사본을 만든다.
  ///
  /// 원작은 전투 직전에 이름·방어도·레벨·특수능력·`E_number` 를 직접 바꿔
  /// 넣는다(Sphinx, Major Mummy, Dragon's tail, Hidra's Head …).
  /// `level` 을 바꾸면 원작과 같이 최대 HP 도 `endurance * level` 로 다시
  /// 계산한다(최대치는 체력 계수 기준이며, 명시적 `hp` 가 있으면 그것을 쓴다).
  Monster withOverrides({
    String? name,
    int? ac,
    int? special,
    int? castLevel,
    int? specialCastLevel,
    int? level,
    int? eNumber,
    int? hp,
  }) {
    final newLevel = level ?? this.level;
    final newStamina = endurance * (newLevel > 0 ? newLevel : 1);
    return Monster(
      eNumber: eNumber ?? this.eNumber,
      name: name ?? this.name,
      strength: strength,
      mentality: mentality,
      endurance: endurance,
      resistance: resistance,
      agility: agility,
      accArms: accArms,
      accMagic: accMagic,
      ac: ac ?? this.ac,
      special: special ?? this.special,
      castLevel: castLevel ?? this.castLevel,
      specialCastLevel: specialCastLevel ?? this.specialCastLevel,
      level: newLevel,
      hp: hp ?? (level == null ? this.hp : newStamina),
      isPoisoned: isPoisoned,
      isUnconscious: isUnconscious,
      isDead: isDead,
    );
  }

  /// 원작 FOEDATA.DAT 기반 75종 몬스터 생성 팩토리 (1..75)
  factory Monster.create(int id) {
    if (id < 1 || id > monsterTemplates.length) {
      id = 1;
    }
    final t = monsterTemplates[id - 1];
    return Monster(
      eNumber: t.eNumber,
      name: t.name,
      strength: t.strength,
      mentality: t.mentality,
      endurance: t.endurance,
      resistance: t.resistance,
      agility: t.agility,
      accArms: t.accArms,
      accMagic: t.accMagic,
      ac: t.ac,
      special: t.special,
      castLevel: t.castLevel,
      specialCastLevel: t.specialCastLevel,
      level: t.level,
    );
  }

  // 1993년 원작 FOEDATA.DAT 75종 전체 몬스터 템플릿 레지스트리
  static final List<Monster> monsterTemplates = [
    Monster(
      eNumber: 1,
      name: 'Orc',
      strength: 8,
      mentality: 0,
      endurance: 8,
      resistance: 0,
      agility: 8,
      accArms: 8,
      accMagic: 0,
      ac: 1,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 1,
    ),
    Monster(
      eNumber: 2,
      name: 'Troll',
      strength: 9,
      mentality: 0,
      endurance: 6,
      resistance: 0,
      agility: 9,
      accArms: 9,
      accMagic: 0,
      ac: 1,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 1,
    ),
    Monster(
      eNumber: 3,
      name: 'Serpent',
      strength: 7,
      mentality: 3,
      endurance: 7,
      resistance: 0,
      agility: 11,
      accArms: 11,
      accMagic: 6,
      ac: 1,
      special: 1,
      castLevel: 1,
      specialCastLevel: 0,
      level: 1,
    ),
    Monster(
      eNumber: 4,
      name: 'Earth Worm',
      strength: 3,
      mentality: 5,
      endurance: 5,
      resistance: 0,
      agility: 6,
      accArms: 11,
      accMagic: 7,
      ac: 1,
      special: 0,
      castLevel: 1,
      specialCastLevel: 0,
      level: 1,
    ),
    Monster(
      eNumber: 5,
      name: 'Dwarf',
      strength: 10,
      mentality: 0,
      endurance: 10,
      resistance: 0,
      agility: 10,
      accArms: 10,
      accMagic: 0,
      ac: 2,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 2,
    ),
    Monster(
      eNumber: 6,
      name: 'Giant',
      strength: 15,
      mentality: 0,
      endurance: 13,
      resistance: 0,
      agility: 8,
      accArms: 8,
      accMagic: 0,
      ac: 2,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 2,
    ),
    Monster(
      eNumber: 7,
      name: 'Phantom',
      strength: 0,
      mentality: 12,
      endurance: 12,
      resistance: 0,
      agility: 0,
      accArms: 0,
      accMagic: 13,
      ac: 0,
      special: 0,
      castLevel: 2,
      specialCastLevel: 0,
      level: 2,
    ),
    Monster(
      eNumber: 8,
      name: 'Wolf',
      strength: 7,
      mentality: 0,
      endurance: 11,
      resistance: 0,
      agility: 15,
      accArms: 15,
      accMagic: 0,
      ac: 1,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 2,
    ),
    Monster(
      eNumber: 9,
      name: 'Imp',
      strength: 8,
      mentality: 8,
      endurance: 10,
      resistance: 20,
      agility: 18,
      accArms: 18,
      accMagic: 10,
      ac: 2,
      special: 0,
      castLevel: 2,
      specialCastLevel: 0,
      level: 3,
    ),
    Monster(
      eNumber: 10,
      name: 'Goblin',
      strength: 11,
      mentality: 0,
      endurance: 13,
      resistance: 0,
      agility: 13,
      accArms: 13,
      accMagic: 0,
      ac: 3,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 3,
    ),
    Monster(
      eNumber: 11,
      name: 'Python',
      strength: 9,
      mentality: 5,
      endurance: 10,
      resistance: 0,
      agility: 13,
      accArms: 13,
      accMagic: 6,
      ac: 1,
      special: 1,
      castLevel: 1,
      specialCastLevel: 0,
      level: 3,
    ),
    Monster(
      eNumber: 12,
      name: 'Insects',
      strength: 6,
      mentality: 4,
      endurance: 8,
      resistance: 0,
      agility: 14,
      accArms: 14,
      accMagic: 15,
      ac: 2,
      special: 1,
      castLevel: 1,
      specialCastLevel: 0,
      level: 3,
    ),
    Monster(
      eNumber: 13,
      name: 'Giant Spider',
      strength: 10,
      mentality: 0,
      endurance: 9,
      resistance: 0,
      agility: 20,
      accArms: 13,
      accMagic: 0,
      ac: 2,
      special: 1,
      castLevel: 0,
      specialCastLevel: 0,
      level: 4,
    ),
    Monster(
      eNumber: 14,
      name: 'Gremlin',
      strength: 10,
      mentality: 0,
      endurance: 10,
      resistance: 0,
      agility: 20,
      accArms: 20,
      accMagic: 0,
      ac: 2,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 4,
    ),
    Monster(
      eNumber: 15,
      name: 'Buzz Bug',
      strength: 13,
      mentality: 0,
      endurance: 11,
      resistance: 0,
      agility: 15,
      accArms: 15,
      accMagic: 0,
      ac: 1,
      special: 1,
      castLevel: 0,
      specialCastLevel: 0,
      level: 4,
    ),
    Monster(
      eNumber: 16,
      name: 'Salamander',
      strength: 12,
      mentality: 2,
      endurance: 13,
      resistance: 0,
      agility: 12,
      accArms: 12,
      accMagic: 10,
      ac: 3,
      special: 1,
      castLevel: 1,
      specialCastLevel: 0,
      level: 4,
    ),
    Monster(
      eNumber: 17,
      name: 'Blood Bat',
      strength: 11,
      mentality: 0,
      endurance: 10,
      resistance: 0,
      agility: 5,
      accArms: 15,
      accMagic: 0,
      ac: 1,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 5,
    ),
    Monster(
      eNumber: 18,
      name: 'Giant Rat',
      strength: 13,
      mentality: 0,
      endurance: 18,
      resistance: 0,
      agility: 10,
      accArms: 10,
      accMagic: 0,
      ac: 2,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 5,
    ),
    Monster(
      eNumber: 19,
      name: 'Skeleton',
      strength: 10,
      mentality: 0,
      endurance: 19,
      resistance: 0,
      agility: 12,
      accArms: 12,
      accMagic: 0,
      ac: 3,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 5,
    ),
    Monster(
      eNumber: 20,
      name: 'Kelpie',
      strength: 8,
      mentality: 13,
      endurance: 8,
      resistance: 0,
      agility: 14,
      accArms: 15,
      accMagic: 17,
      ac: 2,
      special: 0,
      castLevel: 3,
      specialCastLevel: 0,
      level: 5,
    ),
    Monster(
      eNumber: 21,
      name: 'Gazer',
      strength: 15,
      mentality: 8,
      endurance: 11,
      resistance: 0,
      agility: 20,
      accArms: 15,
      accMagic: 15,
      ac: 3,
      special: 0,
      castLevel: 2,
      specialCastLevel: 0,
      level: 6,
    ),
    Monster(
      eNumber: 22,
      name: 'Ghost',
      strength: 0,
      mentality: 15,
      endurance: 10,
      resistance: 0,
      agility: 0,
      accArms: 0,
      accMagic: 15,
      ac: 0,
      special: 0,
      castLevel: 3,
      specialCastLevel: 0,
      level: 6,
    ),
    Monster(
      eNumber: 23,
      name: 'Slime',
      strength: 5,
      mentality: 13,
      endurance: 5,
      resistance: 0,
      agility: 19,
      accArms: 19,
      accMagic: 19,
      ac: 2,
      special: 0,
      castLevel: 2,
      specialCastLevel: 0,
      level: 6,
    ),
    Monster(
      eNumber: 24,
      name: 'Rock-Man',
      strength: 19,
      mentality: 0,
      endurance: 15,
      resistance: 0,
      agility: 10,
      accArms: 10,
      accMagic: 0,
      ac: 5,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 6,
    ),
    Monster(
      eNumber: 25,
      name: 'Kobold',
      strength: 9,
      mentality: 9,
      endurance: 9,
      resistance: 0,
      agility: 9,
      accArms: 9,
      accMagic: 9,
      ac: 2,
      special: 0,
      castLevel: 3,
      specialCastLevel: 0,
      level: 7,
    ),
    Monster(
      eNumber: 26,
      name: 'Mummy',
      strength: 10,
      mentality: 10,
      endurance: 10,
      resistance: 0,
      agility: 10,
      accArms: 10,
      accMagic: 10,
      ac: 3,
      special: 1,
      castLevel: 2,
      specialCastLevel: 0,
      level: 7,
    ),
    Monster(
      eNumber: 27,
      name: 'Devil Hunter',
      strength: 13,
      mentality: 10,
      endurance: 10,
      resistance: 0,
      agility: 10,
      accArms: 10,
      accMagic: 18,
      ac: 3,
      special: 2,
      castLevel: 2,
      specialCastLevel: 0,
      level: 7,
    ),
    Monster(
      eNumber: 28,
      name: 'Crazy One',
      strength: 9,
      mentality: 9,
      endurance: 10,
      resistance: 0,
      agility: 5,
      accArms: 5,
      accMagic: 13,
      ac: 1,
      special: 0,
      castLevel: 3,
      specialCastLevel: 0,
      level: 7,
    ),
    Monster(
      eNumber: 29,
      name: 'Ogre',
      strength: 19,
      mentality: 0,
      endurance: 19,
      resistance: 0,
      agility: 9,
      accArms: 12,
      accMagic: 0,
      ac: 4,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 8,
    ),
    Monster(
      eNumber: 30,
      name: 'Headless',
      strength: 10,
      mentality: 0,
      endurance: 15,
      resistance: 0,
      agility: 10,
      accArms: 10,
      accMagic: 0,
      ac: 3,
      special: 2,
      castLevel: 0,
      specialCastLevel: 0,
      level: 8,
    ),
    Monster(
      eNumber: 31,
      name: 'Mud-Man',
      strength: 10,
      mentality: 0,
      endurance: 15,
      resistance: 0,
      agility: 10,
      accArms: 10,
      accMagic: 0,
      ac: 7,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 8,
    ),
    Monster(
      eNumber: 32,
      name: 'Hell Cat',
      strength: 10,
      mentality: 15,
      endurance: 11,
      resistance: 0,
      agility: 18,
      accArms: 18,
      accMagic: 16,
      ac: 2,
      special: 2,
      castLevel: 3,
      specialCastLevel: 0,
      level: 8,
    ),
    Monster(
      eNumber: 33,
      name: 'Wisp',
      strength: 5,
      mentality: 16,
      endurance: 10,
      resistance: 0,
      agility: 20,
      accArms: 20,
      accMagic: 20,
      ac: 2,
      special: 0,
      castLevel: 4,
      specialCastLevel: 0,
      level: 9,
    ),
    Monster(
      eNumber: 34,
      name: 'Basilisk',
      strength: 10,
      mentality: 15,
      endurance: 12,
      resistance: 0,
      agility: 20,
      accArms: 20,
      accMagic: 10,
      ac: 2,
      special: 1,
      castLevel: 2,
      specialCastLevel: 0,
      level: 9,
    ),
    Monster(
      eNumber: 35,
      name: 'Sprite',
      strength: 0,
      mentality: 20,
      endurance: 2,
      resistance: 80,
      agility: 20,
      accArms: 20,
      accMagic: 20,
      ac: 0,
      special: 3,
      castLevel: 5,
      specialCastLevel: 0,
      level: 9,
    ),
    Monster(
      eNumber: 36,
      name: 'Vampire',
      strength: 15,
      mentality: 13,
      endurance: 14,
      resistance: 20,
      agility: 17,
      accArms: 17,
      accMagic: 15,
      ac: 3,
      special: 1,
      castLevel: 2,
      specialCastLevel: 0,
      level: 9,
    ),
    Monster(
      eNumber: 37,
      name: 'Molten Monster',
      strength: 8,
      mentality: 0,
      endurance: 20,
      resistance: 50,
      agility: 8,
      accArms: 16,
      accMagic: 0,
      ac: 3,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 10,
    ),
    Monster(
      eNumber: 38,
      name: 'Great Lich',
      strength: 10,
      mentality: 10,
      endurance: 11,
      resistance: 10,
      agility: 18,
      accArms: 10,
      accMagic: 10,
      ac: 4,
      special: 2,
      castLevel: 3,
      specialCastLevel: 0,
      level: 10,
    ),
    Monster(
      eNumber: 39,
      name: 'Rampager',
      strength: 20,
      mentality: 0,
      endurance: 19,
      resistance: 0,
      agility: 19,
      accArms: 19,
      accMagic: 0,
      ac: 3,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 10,
    ),
    Monster(
      eNumber: 40,
      name: 'Mutant',
      strength: 0,
      mentality: 10,
      endurance: 15,
      resistance: 0,
      agility: 0,
      accArms: 0,
      accMagic: 20,
      ac: 3,
      special: 0,
      castLevel: 3,
      specialCastLevel: 0,
      level: 10,
    ),
    Monster(
      eNumber: 41,
      name: 'Rotten Corpse',
      strength: 15,
      mentality: 15,
      endurance: 15,
      resistance: 60,
      agility: 15,
      accArms: 15,
      accMagic: 15,
      ac: 2,
      special: 2,
      castLevel: 3,
      specialCastLevel: 0,
      level: 11,
    ),
    Monster(
      eNumber: 42,
      name: 'Gagoyle',
      strength: 10,
      mentality: 0,
      endurance: 20,
      resistance: 10,
      agility: 10,
      accArms: 10,
      accMagic: 0,
      ac: 6,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 11,
    ),
    Monster(
      eNumber: 43,
      name: 'Wivern',
      strength: 10,
      mentality: 10,
      endurance: 9,
      resistance: 30,
      agility: 20,
      accArms: 20,
      accMagic: 9,
      ac: 3,
      special: 2,
      castLevel: 3,
      specialCastLevel: 0,
      level: 11,
    ),
    Monster(
      eNumber: 44,
      name: 'Grim Death',
      strength: 16,
      mentality: 16,
      endurance: 16,
      resistance: 50,
      agility: 16,
      accArms: 16,
      accMagic: 16,
      ac: 2,
      special: 2,
      castLevel: 3,
      specialCastLevel: 0,
      level: 12,
    ),
    Monster(
      eNumber: 45,
      name: 'Griffin',
      strength: 15,
      mentality: 15,
      endurance: 15,
      resistance: 0,
      agility: 15,
      accArms: 14,
      accMagic: 14,
      ac: 3,
      special: 2,
      castLevel: 3,
      specialCastLevel: 0,
      level: 12,
    ),
    Monster(
      eNumber: 46,
      name: 'Evil Soul',
      strength: 0,
      mentality: 20,
      endurance: 10,
      resistance: 0,
      agility: 0,
      accArms: 0,
      accMagic: 15,
      ac: 0,
      special: 3,
      castLevel: 4,
      specialCastLevel: 0,
      level: 12,
    ),
    Monster(
      eNumber: 47,
      name: 'Cyclops',
      strength: 20,
      mentality: 0,
      endurance: 20,
      resistance: 10,
      agility: 20,
      accArms: 20,
      accMagic: 0,
      ac: 4,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 13,
    ),
    Monster(
      eNumber: 48,
      name: 'Dancing-Swd',
      strength: 15,
      mentality: 20,
      endurance: 6,
      resistance: 20,
      agility: 20,
      accArms: 20,
      accMagic: 20,
      ac: 0,
      special: 2,
      castLevel: 4,
      specialCastLevel: 0,
      level: 13,
    ),
    Monster(
      eNumber: 49,
      name: 'Hydra',
      strength: 15,
      mentality: 10,
      endurance: 20,
      resistance: 40,
      agility: 18,
      accArms: 18,
      accMagic: 12,
      ac: 8,
      special: 1,
      castLevel: 3,
      specialCastLevel: 0,
      level: 13,
    ),
    Monster(
      eNumber: 50,
      name: 'Stheno',
      strength: 20,
      mentality: 20,
      endurance: 20,
      resistance: 255,
      agility: 10,
      accArms: 10,
      accMagic: 10,
      ac: 255,
      special: 1,
      castLevel: 3,
      specialCastLevel: 0,
      level: 14,
    ),
    Monster(
      eNumber: 51,
      name: 'Euryale',
      strength: 20,
      mentality: 20,
      endurance: 15,
      resistance: 255,
      agility: 10,
      accArms: 15,
      accMagic: 10,
      ac: 255,
      special: 2,
      castLevel: 3,
      specialCastLevel: 0,
      level: 14,
    ),
    Monster(
      eNumber: 52,
      name: 'Medusa',
      strength: 15,
      mentality: 10,
      endurance: 16,
      resistance: 50,
      agility: 15,
      accArms: 15,
      accMagic: 10,
      ac: 4,
      special: 3,
      castLevel: 3,
      specialCastLevel: 0,
      level: 14,
    ),
    Monster(
      eNumber: 53,
      name: 'Minotaur',
      strength: 15,
      mentality: 7,
      endurance: 20,
      resistance: 40,
      agility: 20,
      accArms: 20,
      accMagic: 15,
      ac: 10,
      special: 0,
      castLevel: 3,
      specialCastLevel: 0,
      level: 15,
    ),
    Monster(
      eNumber: 54,
      name: 'Dragon',
      strength: 15,
      mentality: 7,
      endurance: 20,
      resistance: 50,
      agility: 18,
      accArms: 20,
      accMagic: 15,
      ac: 9,
      special: 2,
      castLevel: 4,
      specialCastLevel: 0,
      level: 15,
    ),
    Monster(
      eNumber: 55,
      name: 'Dark Soul',
      strength: 0,
      mentality: 20,
      endurance: 40,
      resistance: 60,
      agility: 0,
      accArms: 0,
      accMagic: 20,
      ac: 0,
      special: 0,
      castLevel: 5,
      specialCastLevel: 0,
      level: 15,
    ),
    Monster(
      eNumber: 56,
      name: 'Hell Fire',
      strength: 15,
      mentality: 20,
      endurance: 30,
      resistance: 30,
      agility: 15,
      accArms: 15,
      accMagic: 15,
      ac: 0,
      special: 3,
      castLevel: 5,
      specialCastLevel: 0,
      level: 16,
    ),
    Monster(
      eNumber: 57,
      name: 'Astral Mud',
      strength: 13,
      mentality: 20,
      endurance: 25,
      resistance: 40,
      agility: 19,
      accArms: 19,
      accMagic: 10,
      ac: 9,
      special: 3,
      castLevel: 4,
      specialCastLevel: 0,
      level: 16,
    ),
    Monster(
      eNumber: 58,
      name: 'Reaper',
      strength: 15,
      mentality: 20,
      endurance: 33,
      resistance: 70,
      agility: 20,
      accArms: 20,
      accMagic: 20,
      ac: 5,
      special: 1,
      castLevel: 3,
      specialCastLevel: 0,
      level: 17,
    ),
    Monster(
      eNumber: 59,
      name: 'Crab God',
      strength: 20,
      mentality: 20,
      endurance: 30,
      resistance: 20,
      agility: 18,
      accArms: 18,
      accMagic: 19,
      ac: 7,
      special: 2,
      castLevel: 4,
      specialCastLevel: 0,
      level: 17,
    ),
    Monster(
      eNumber: 60,
      name: 'Wraith',
      strength: 0,
      mentality: 24,
      endurance: 35,
      resistance: 50,
      agility: 15,
      accArms: 0,
      accMagic: 20,
      ac: 2,
      special: 3,
      castLevel: 4,
      specialCastLevel: 0,
      level: 18,
    ),
    Monster(
      eNumber: 61,
      name: 'Death Skull',
      strength: 0,
      mentality: 20,
      endurance: 40,
      resistance: 80,
      agility: 0,
      accArms: 0,
      accMagic: 20,
      ac: 0,
      special: 2,
      castLevel: 5,
      specialCastLevel: 0,
      level: 18,
    ),
    Monster(
      eNumber: 62,
      name: 'Draconian',
      strength: 30,
      mentality: 20,
      endurance: 30,
      resistance: 60,
      agility: 18,
      accArms: 18,
      accMagic: 18,
      ac: 7,
      special: 2,
      castLevel: 5,
      specialCastLevel: 1,
      level: 19,
    ),
    Monster(
      eNumber: 63,
      name: 'Death Knight',
      strength: 35,
      mentality: 0,
      endurance: 35,
      resistance: 50,
      agility: 20,
      accArms: 20,
      accMagic: 0,
      ac: 6,
      special: 3,
      castLevel: 0,
      specialCastLevel: 1,
      level: 19,
    ),
    Monster(
      eNumber: 64,
      name: 'Guardian-Lft',
      strength: 25,
      mentality: 0,
      endurance: 40,
      resistance: 70,
      agility: 20,
      accArms: 18,
      accMagic: 0,
      ac: 5,
      special: 2,
      castLevel: 0,
      specialCastLevel: 0,
      level: 20,
    ),
    Monster(
      eNumber: 65,
      name: 'Guardian-Rgt',
      strength: 25,
      mentality: 0,
      endurance: 40,
      resistance: 40,
      agility: 20,
      accArms: 20,
      accMagic: 0,
      ac: 7,
      special: 2,
      castLevel: 0,
      specialCastLevel: 0,
      level: 20,
    ),
    Monster(
      eNumber: 66,
      name: 'Mega-Robo',
      strength: 40,
      mentality: 0,
      endurance: 50,
      resistance: 0,
      agility: 19,
      accArms: 19,
      accMagic: 0,
      ac: 10,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 21,
    ),
    Monster(
      eNumber: 67,
      name: 'Ancient Evil',
      strength: 0,
      mentality: 20,
      endurance: 60,
      resistance: 100,
      agility: 18,
      accArms: 0,
      accMagic: 20,
      ac: 5,
      special: 0,
      castLevel: 6,
      specialCastLevel: 2,
      level: 22,
    ),
    Monster(
      eNumber: 68,
      name: 'Lord Ahn',
      strength: 40,
      mentality: 20,
      endurance: 60,
      resistance: 100,
      agility: 35,
      accArms: 20,
      accMagic: 20,
      ac: 10,
      special: 3,
      castLevel: 5,
      specialCastLevel: 3,
      level: 23,
    ),
    Monster(
      eNumber: 69,
      name: 'Frost Dragon',
      strength: 15,
      mentality: 7,
      endurance: 20,
      resistance: 50,
      agility: 18,
      accArms: 20,
      accMagic: 15,
      ac: 9,
      special: 2,
      castLevel: 4,
      specialCastLevel: 0,
      level: 24,
    ),
    Monster(
      eNumber: 70,
      name: 'ArchiDraconian',
      strength: 30,
      mentality: 20,
      endurance: 30,
      resistance: 60,
      agility: 18,
      accArms: 18,
      accMagic: 18,
      ac: 7,
      special: 2,
      castLevel: 5,
      specialCastLevel: 1,
      level: 25,
    ),
    Monster(
      eNumber: 71,
      name: 'Panzer Viper',
      strength: 35,
      mentality: 0,
      endurance: 40,
      resistance: 80,
      agility: 20,
      accArms: 20,
      accMagic: 0,
      ac: 9,
      special: 1,
      castLevel: 0,
      specialCastLevel: 0,
      level: 26,
    ),
    Monster(
      eNumber: 72,
      name: 'Black Knight',
      strength: 35,
      mentality: 0,
      endurance: 35,
      resistance: 50,
      agility: 20,
      accArms: 20,
      accMagic: 0,
      ac: 6,
      special: 3,
      castLevel: 0,
      specialCastLevel: 1,
      level: 27,
    ),
    Monster(
      eNumber: 73,
      name: 'ArchiMonk',
      strength: 20,
      mentality: 0,
      endurance: 50,
      resistance: 70,
      agility: 20,
      accArms: 20,
      accMagic: 0,
      ac: 5,
      special: 0,
      castLevel: 0,
      specialCastLevel: 0,
      level: 28,
    ),
    Monster(
      eNumber: 74,
      name: 'ArchiMage',
      strength: 10,
      mentality: 19,
      endurance: 30,
      resistance: 70,
      agility: 10,
      accArms: 10,
      accMagic: 19,
      ac: 4,
      special: 0,
      castLevel: 6,
      specialCastLevel: 0,
      level: 29,
    ),
    Monster(
      eNumber: 75,
      name: 'Neo-Necromancer',
      strength: 40,
      mentality: 20,
      endurance: 60,
      resistance: 100,
      agility: 30,
      accArms: 20,
      accMagic: 20,
      ac: 10,
      special: 3,
      castLevel: 6,
      specialCastLevel: 3,
      level: 30,
    ),
  ];
}
