"""Generate presentation-only Korean spacing using Kiwi (kiwipiepy).

Source replay strings and game rules remain in their original form. Only
whitespace may change. Run from this project after installing kiwipiepy.
"""
import gzip
import json
from pathlib import Path
import re

from kiwipiepy import Kiwi

ROOT = Path(__file__).resolve().parents[1]


def compact(text):
    return re.sub(r"\s+", "", text)


def main():
    baseline = json.loads(gzip.decompress(
        (ROOT / "test/fixtures/source_dialogue_migration_baseline.json.gz").read_bytes()
    ))
    paragraphs = set()
    for sample in baseline["samples"]:
        pending = []
        highlighted = None
        for event in sample["expected"]["trace"]:
            if event[0] in ("print", "cprint"):
                text = event[2] if event[0] == "print" else "".join(event[3:6])
                # The trace logs cPrint and its delegated Print separately.
                if event[0] == "print" and text == highlighted:
                    highlighted = None
                    continue
                highlighted = text if event[0] == "cprint" else None
                if text.strip():
                    pending.append(text.strip())
                    continue
            if pending:
                # DOS wraps in the middle of Korean words. Rejoin before the
                # morphological spacing pass instead of inserting a space.
                paragraphs.add("".join(pending))
                pending = []
        if pending:
            paragraphs.add("".join(pending))
    kiwi = Kiwi()
    for word in ("텔리포트", "피라밋", "Necromancer", "MENACE"):
        kiwi.add_user_word(word, "NNP")
    corrections = {}
    for paragraph in sorted(paragraphs):
        corrected = re.sub(r"[ \t]+", " ", kiwi.space(paragraph, reset_whitespace=True))
        if compact(paragraph) != compact(corrected):
            raise ValueError("Spacing correction changed non-whitespace text")
        corrections[compact(paragraph)] = corrected
    output = ROOT / "lib/data/dialogue_spacing.dart"
    entries = []
    for key, value in sorted(corrections.items()):
        encode = lambda text: json.dumps(text, ensure_ascii=False).replace("$", "\\$")
        entries.append(f"  {encode(key)}: {encode(value)},")
    output.write_text(
        "// Generated by tool/correct_dialogue_spacing.py using Kiwi.\n"
        "// Display-only whitespace corrections; source dialogue is preserved.\n"
        "const dialogueSpacing = <String, String>{\n" + "\n".join(entries) + "\n};\n",
        encoding="utf-8",
    )
    print(f"Checked and generated {len(corrections)} dialogue paragraphs")


if __name__ == "__main__":
    main()
