#!/usr/bin/env python3
"""Export source speech presentation metadata, without gameplay rules.

No conditions or effects are interpreted. Unambiguous literal Print/cPrint,
Message, talk and their following key waits retain source colors/page breaks.
Dynamic statements and conflicting uses stay with their explicit Dart adapters.
"""
import argparse
import json
import re
from pathlib import Path
from audit_lorespec import decode
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'lib/logic/lore_source_speech.dart'
CALL = re.compile(r"\b(Print|cPrint|talk|message)\s*\((.*?)\)\s*;", re.I)
LITERAL = re.compile(r"'((?:[^']|'')*)'")

def collect(units=('LORESPEC', 'LOREENT')):
    uses = {}
    for unit in units:
        previous = None
        for number, raw in enumerate((ROOT / f'repo_source/LORE_1993_src/{unit}.PAS').read_bytes().splitlines(), 1):
            line = decode(raw)
            for call in CALL.finditer(line):
                kind, args = call.groups()
                kind = kind.lower()
                pieces = LITERAL.findall(args)
                # Ignore variable interpolation; native scene/name adapters own it.
                rest = LITERAL.sub("''", args)
                if not pieces or re.search(r"[A-Za-z_]", rest):
                    previous = None
                    continue
                text = ''.join(p.replace("''", "'") for p in pieces)
                colors = re.match(r'\s*(\d+)', args)
                color = int(colors[1]) if colors else 7
                spans = []
                if kind == 'cprint':
                    two = re.match(r'\s*(\d+)\s*,\s*(\d+)\s*,', args)
                    if two and len(pieces) == 3:
                        spans = [(int(two[1]) if i != 1 else int(two[2]),
                                  piece.replace("''", "'"))
                                 for i, piece in enumerate(pieces) if piece]
                record = dict(spans=spans, color=color, wait=kind == 'talk', blank=False,
                              log=kind == 'message', source=f'{unit}:{number}')
                if kind == 'talk' and not text:
                    if previous is not None:
                        previous['wait'] = True
                        previous['blank'] = True
                    continue
                if text:
                    uses.setdefault(text, []).append(record)
                previous = record
            if re.search(r'\bPressAnyKey\s*;', line, re.I) and previous is not None:
                previous['wait'] = True
            # Source Clear begins a new page even when no literal call preceded it.
            if re.search(r'\bClear\s*;', line, re.I):
                previous = None
    result = {}
    for text, records in uses.items():
        signatures = {(r['color'], r['wait'], r['blank'], r['log'], tuple(r['spans'])) for r in records}
        if len(signatures) == 1:
            result[text] = records[0]
    return result

def collect_patterns():
    patterns = []
    shape = re.compile(r"^\s*(\d+)\s*,\s*(\d+)\s*,\s*'((?:[^']|'')*)'\s*,\s*[A-Za-z_]\w*(?:\[\w+\])?\s*,\s*'((?:[^']|'')*)'\s*$")
    for unit in ('LORESPEC', 'LOREENT', 'LORETALK', 'LOREMENU', 'LORESUB'):
        for raw in (ROOT / f'repo_source/LORE_1993_src/{unit}.PAS').read_bytes().splitlines():
            for call in CALL.finditer(decode(raw)):
                if call[1].lower() != 'cprint':
                    continue
                m = shape.fullmatch(call[2])
                if m and (m[3] or m[4]):
                    patterns.append((int(m[1]), int(m[2]),
                                     m[3].replace("''", "'"), m[4].replace("''", "'")))
    return list(dict.fromkeys(patterns))

def dart_text(text):
    return json.dumps(text, ensure_ascii=False).replace('$', r'\$')

def render():
    lines = ['// GENERATED by tool/export_source_speech.py. Presentation only.',
             '// Literal source colors, Message vs Print, and explicit key waits.',
             'class LoreSourceSpeech {', '  const LoreSourceSpeech._();']
    for name, units in [('lines', ('LORESPEC', 'LOREENT')),
                        ('talkLines', ('LORETALK',))]:
        lines.append(f'  static const Map<String, ({{int color, bool wait, bool blank, bool log}})> {name} = {{')
        for text, r in sorted(collect(units).items()):
            lines += [f"    // {r['source']}",
                      f"    {dart_text(text)}: (color: {r['color']}, wait: {str(r['wait']).lower()}, blank: {str(r['blank']).lower()}, log: {str(r['log']).lower()}),"]
        lines.append('  };')
    lines.append('  static const Map<String, List<(int, String)>> spans = {')
    for text, r in sorted(collect(('LORESPEC', 'LOREENT', 'LORETALK', 'LOREMENU', 'LORESUB')).items()):
        if r['spans']:
            spans = ', '.join(f'({color}, {dart_text(part)})' for color, part in r['spans'])
            lines += [f"    // {r['source']}", f'    {dart_text(text)}: [{spans}],']
    lines.append('  };')
    lines.append('  static const patterns = <(int, int, String, String)>[')
    for color, word, prefix, suffix in collect_patterns():
        lines.append(f'    ({color}, {word}, {dart_text(prefix)}, {dart_text(suffix)}),')
    return '\n'.join(lines + ['  ];', '}', ''])

if __name__ == '__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check', action='store_true');args=parser.parse_args()
    output=render()
    if args.check:
        if OUT.read_text() != output: raise SystemExit('Source speech metadata is stale')
    else: OUT.write_text(output)
