"""Inventory source memory risks; this is a review index, not a Pascal compiler."""

import argparse
import hashlib
import re
from collections import Counter
from pathlib import Path

from build_port_contract_ledger import strip_pascal_comments
from source_branch_inventory import PLATFORM_UNITS, program_files

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "repo_source/LORE_1993_src"
OUTPUT = ROOT / "docs/audits/source_memory_audit.md"


def classify(line):
    kinds = []
    if re.search(r"\b(shl|shr|xor)\b", line, re.I):
        kinds.append("shift/xor")
    if re.search(r"\bbit[1-8]\b", line, re.I):
        kinds.append("bit mask")
    if re.search(r"\b(div|mod)\b", line, re.I):
        kinds.append("div/mod")
    if re.search(r"\barray\s*\[", line, re.I):
        kinds.append("array bounds")
    if re.search(r"@\s*party\.etc\s*\[", line, re.I):
        kinds.append("etc pointer alias")
    if re.search(r"\bmap\s*\[[^\]]+\]\s*:=", line, re.I):
        kinds.append("map write")
    indices = re.findall(r"\betc\s*\[([^\]]+)\]", line, re.I)
    if any(not re.fullmatch(r"\s*\d+\s*", index) for index in indices):
        kinds.append("computed etc index")
    if re.search(r"\betc\s*\[[^\]]+\]\s*:=|\b(?:inc|dec)\s*\(\s*party\.etc", line, re.I):
        kinds.append("etc write")
    return kinds


def render():
    rows = []
    hashes = []
    for unit in program_files():
        filename = f"{unit}.PAS"
        if filename in PLATFORM_UNITS:
            continue
        data = (SOURCE / filename).read_bytes()
        hashes.append((filename, hashlib.sha256(data).hexdigest()))
        # Reuse the existing source auditor's removal of comments and strings;
        # preserving newlines makes positions refer to the unmodified DOS source.
        for line_number, line in enumerate(strip_pascal_comments(data).splitlines(), 1):
            kinds = classify(line)
            if kinds:
                code = " ".join(line.split()).replace("|", "\\|")
                rows.append((filename, line_number, kinds, code))
    counts = Counter(kind for _, _, kinds, _ in rows for kind in kinds)
    lines = [
        "# LORE source memory review index", "",
        "Generated by `python tool/audit_source_memory.py`; `--check` detects drift.", "",
        "Scope: reachable main-program units, excluding DOS graphics/audio units.",
        "One row is a candidate source line, not a verified expression or completion claim.",
        "Multiple statements on one line remain together. This scan does not infer operand",
        "types, overflow sites, implicit `with party` aliases, or loop reachability.", "",
        "## Review categories", "", "| Category | Candidate lines |", "| --- | ---: |",
        *[f"| {kind} | {count} |" for kind, count in sorted(counts.items())], "",
        "## Source locations", "", "| Source | Review | Code (strings removed) |", "| --- | --- | --- |",
        *[f"| {filename}:{line} | {', '.join(kinds)} | `{code}` |" for filename, line, kinds, code in rows], "",
        "## Source SHA-256", "", "| Source | SHA-256 |", "| --- | --- |",
        *[f"| {filename} | `{digest}` |" for filename, digest in hashes], "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("Source memory review index is stale")
    else:
        OUTPUT.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
